- name: bug
  color: "d73a4a"
  description: "Something isn't working"
- name: enhancement
  color: "a2eeef"
  description: "New feature or request"
- name: documentation
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: question
  color: "d876e3"
  description: "Further information is requested"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: security
  color: "e11d48"
  description: "Security-related issue"
- name: performance
  color: "f59e0b"
  description: "Performance improvement"
- name: stale
  color: "cbd5e1"
  description: "No recent activity"
- name: pinned
  color: "1d4ed8"
  description: "Pinned issue — won't be auto-closed"
- name: duplicate
  color: "cfd3d7"
  description: "This issue or PR already exists"
- name: wontfix
  color: "ffffff"
  description: "This will not be worked on"
- name: "breaking change"
  color: "dc2626"
  description: "Introduces a breaking change"
- name: sdk
  color: "6366f1"
  description: "Core TypeScript SDK"
- name: rust
  color: "dea584"
  description: "Rust vanity generator"
- name: mcp
  color: "06b6d4"
  description: "MCP server"
- name: scripts
  color: "84cc16"
  description: "Shell scripts"
- name: ci
  color: "64748b"
  description: "CI/CD and build system"
- name: dependencies
  color: "0366d6"
  description: "Dependency updates"

